(window.dullscriptWebpackJsonp=window.dullscriptWebpackJsonp||[]).push([[26],{1312:function(y,C,b){function a(m,h,x){this.$Rc=0;this.ZTb=null;this.bfb=this.rXb=this.vhb=0;this.cRc=m;this.yWa=h;this.y9=x;this.cRc=262144>m?m:262144;this.Mrg=this.cRc-4*(this.yWa+25);this.reset()}function c(m,h,x,u,w,v,t,z,D){z=void 0===z?null:z;D=void 0===D?null:D;this.T=this.G=0;this.C=this.M=null;this.D=0;this.G=v;this.T=u;this.M=m;this.C=h;this.D=1E3*w+x;if(void 0===t?0:t)this.O=1;z&&(this.A=z);D&&(this.E=D)}function e(m,
h,x,u,w){this.T=m;this.L=h;this.S=x;this.I=u;this.V=w}function f(m,h,x,u,w,v){m&&(this.N=m);h&&(this.S=h);x&&(this.M=x);u&&(this.F=u);null!=w&&(this.L=w);null!=v&&(this.C=v)}b.r(C);y=b(0);var l=b(15);Object(y.a)(f,"SerializableExceptionEntry",null,[]);Object(y.a)(e,"SerializableLogCache",null,[]);c.prototype.DVg=function(){if(!this.E)return 0;var m=7,h=0;this.E.N&&(m+=6+c.u$(this.E.N),h++);this.E.S&&(m+=6+c.u$(this.E.S),h++);this.E.M&&(m+=6+c.u$(this.E.M),h++);this.E.F&&(m+=6+c.u$(this.E.F),h++);
this.E.L&&(m+=6+c.u$(this.E.L),h++);this.E.C&&(m+=6+c.u$(this.E.C),h++);1<h&&(m+=h-1);return m};c.prototype.d0g=function(){var m=b(1312).LogCache.Xsi+c.u$(this.G)+c.u$(this.T)+this.M.length+c.u$(this.C)+c.u$(this.D)+this.DVg();1===this.O&&(m+=6);if(this.A){m+=7;for(var h=0,x=this.A.length;h<x;++h)m+=this.A[h].length+3}return m};c.u$=function(m){return(""+m).length};Object(y.a)(c,"SerializableLogEntry",null,[]);var n=b(396);b.d(C,"LogCache",function(){return a});a.prototype.reset=function(){this.ZTb=
[];this.vhb=25;this.$Rc=(new Date).getTime()};a.prototype.YAg=function(m){if(m){m.message=this.xNb(m.message,"message",m.tag);var h=m.H9c;h&&(h.name=this.xNb(h.name,"Exception.Name",m.tag),h.stack=this.xNb(h.stack,"Exception.Stack",m.tag),h.message=this.xNb(h.message,"Exception.Message",m.tag),h.file=this.xNb(h.file,"Exception.File",m.tag));if(m.fh)for(var x=0;x<m.fh.length;x++)m.fh[x].length>this.yWa&&(m.fh[x]=m.fh[x].substr(0,this.yWa-13)+"... [trimmed]",l.ULS.sendTraceTag(3465240,100,50,"Trimmed arg {0} for log {1}",
x,n.a(m.tag)));h=h?new f(h.name,h.stack,h.message,h.file,h.line,h.column):null;m=new c(m.message,m.category,m.level,m.timestamp-this.$Rc,m.Xtd,m.tag,m.rii,m.fh,h);h=m.d0g();0<this.rXb&&h+this.vhb>this.rXb&&(x=this.count,this.reset(),l.ULS.sendTraceTag(0,100,15,"The log size is too large to be accepted by the server, throwing away {0} logs.",x));Array.add(this.ZTb,m);this.vhb+=h}};a.prototype.xNb=function(m,h,x){var u=m;m&&m.length>this.yWa&&(u=m.substr(0,this.yWa-13)+"... [trimmed]",l.ULS.sendTraceTag(3465240,
100,50,"Trimmed {0} for log {1}",h,n.a(x)));return u};a.prototype.serialize=function(){return l.ULS.Jc(new e(this.$Rc,this.ZTb,this.y9,this.bfb,1))};Ck.Object.defineProperties(a.prototype,{count:{configurable:!0,enumerable:!0,get:function(){return this.ZTb.length}},dCc:{configurable:!0,enumerable:!0,get:function(){return this.rXb},set:function(m){this.rXb=m}},kfi:{configurable:!0,enumerable:!0,get:function(){return this.vhb>this.Mrg}},eSd:{configurable:!0,enumerable:!0,get:function(){return this.cRc}},
Btd:{configurable:!0,enumerable:!0,get:function(){return this.yWa}}});a.Xsi=31;Object(y.a)(a,"LogCache",null,[51,52])},1459:function(y,C,b){function a(mb){this.rbe=null;this.Ini=mb}function c(mb){var Pa=la.call(this)||this;Pa.Jda=mb;Pa.Tb();return Pa}function e(mb){var Pa=va.call(this)||this;Pa.$2b=mb;Sys.Application.registerDisposableObject(Pa);return Pa}function f(){}function l(mb){mb=n.call(this,mb,!1,ba.AFrameworkApplication.Jd,ka.a.instance.Lh("Common.IRefreshableAppSettings")||ba.AFrameworkApplication.fa,
ka.a.instance.Lh("Common.IRefreshableAppSettings"))||this;mb.tMj="usu";mb.qMj="ufu";mb.xb=null;mb.Pa=new Ya.a;return mb}function n(mb,Pa,Da,Ta,Sa){mb=x.call(this,ba.AFrameworkApplication.userSessionId,n.gEh(mb,Pa,Da),new u(void 0,ba.AFrameworkApplication.TZh(),Ta.Dd("BulsUploadFrequencyInMs",6E4),void 0,void 0,void 0,void 0,ba.AFrameworkApplication.U0b))||this;mb.sG=null;mb.Plb=null;mb.GPc=null;mb.dh=Da;mb.oCa=Ta;mb.Mlb=mb.oCa.Va("RemoteUlsETag");mb.Mlb&&n.EIf(mb.oCa.Va("RemoteUlsSuppressions"));
Sa&&Sa.eVc(Object(N.a)(mb,mb.kQi,"onSettingsRefreshed"));return mb}function m(mb){var Pa=La.call(this)||this;Pa.fh=mb;return Pa}function h(mb,Pa,Da,Ta){this.bfb=mb;this.ase=Pa;this.sessionId=Da;this.version=Ta}function x(mb,Pa,Da){Da=void 0===Da?null:Da;this.kSb=0;this.XHc=!1;this.iDb=0;this.Chb=null;this.$lb=0;this.Pg=null;this.QOd=this._disposing=!1;this.WB=this.XRc=this.KQb=this.HRb=0;this.dvc=!1;this.HUa=0;Da||(Da=new u);this.zQc=mb;this.f8=Pa;this.f8.toLowerCase().startsWith("http:")&&document.URL.toLowerCase().startsWith("https:")&&
B.ULS.disable();this.yxg=Da.ldg;this.Ywg=Da.m8f;this.Hmg=Da.wGe;this.zxg=Da.Lre;this.lkg=Da.Ire;this.Fqa=new qa.LogCache(Da.eSd,Da.Btd,mb);this.Fqa.dCc=Da.dCc;this.kKd();this.YRf();this.ZRf()}function u(mb,Pa,Da,Ta,Sa,Cb,cc,nc){mb=void 0===mb?null:mb;Pa=void 0===Pa?null:Pa;Da=void 0===Da?null:Da;Ta=void 0===Ta?null:Ta;Sa=void 0===Sa?null:Sa;Cb=void 0===Cb?null:Cb;cc=void 0===cc?null:cc;nc=void 0===nc?null:nc;this.Btd=3072;this.eSd=65536;this.ldg=6E4;this.m8f=2E3;this.wGe=1E4;this.Lre=5E3;this.Ire=
!1;this.dCc=0;null!=mb&&(this.Btd=mb);null!=Pa&&(this.eSd=Pa);null!=Da&&(this.ldg=Da);null!=Ta&&(this.m8f=Ta);null!=Sa&&(this.wGe=Sa);null!=Cb&&(this.Lre=Cb);null!=cc&&(this.Ire=cc);null!=nc&&0<nc&&(this.dCc=nc)}function w(){}function v(){}function t(mb,Pa,Da,Ta,Sa){this.fFa=mb;this.EUa=Pa;this.r1=Da;this.TEc=Ta;this.oqg=Sa}function z(){this.File=this.Message=null;this.Column=this.Line=0;this.ClientAppVersion=this.Stack=null;this.AppMode=this.AppType=0;this.DeobfuscateWithSourceMaps=!1;this.DataPlumber=
this.SessionStartInfoJson=null;this.IsShuttingDown=!1;this.ErrorName=this.Flight=null}function D(){this.tb=null}function A(){$addHandler(document,"securitypolicyviolation",Object(N.a)(this,this.sBf,"onSecurityPolicyViolationEventHandler"))}b.r(C);y=b(724);C=b(0);var B=b(15),N=b(82),P=b(80);A.prototype.sBf=function(mb){mb=mb.rawEvent;var Pa=mb.blockedURI;Pa=P.a.gda(Pa);var Da={};Da.effectiveDirective=mb.effectiveDirective;Da.violatedDirective=mb.violatedDirective;Da.originalPolicy=mb.originalPolicy;
Da.blockedURI=Pa;Da.disposition=mb.disposition;B.ULS.sendTraceTag(588084128,306,15,"{0}",Da)};A.prototype.dispose=function(){$removeHandler(document,"securitypolicyviolation",Object(N.a)(this,this.sBf,"onSecurityPolicyViolationEventHandler"))};Object(C.a)(A,"ContentSecurityPolicyListener",null,[3]);var Q=b(257);D.prototype.init=function(){this.tb.resolve("Common.App.ContentSecurityPolicy.ContentSecurityPolicyListener")};D.prototype.dispose=function(){var mb=this.tb.Lh("Common.App.ContentSecurityPolicy.ContentSecurityPolicyListener");
mb&&mb.dispose()};D.prototype.fi=function(mb){this.tb=mb;this.tb.register(A,"Common.App.ContentSecurityPolicy.ContentSecurityPolicyListener").Hc().Oc(function(){return new A})};D.main=function(){Q.a.instance.gj(new D)};Ck.Object.defineProperties(D.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return"Common.App.ContentSecurityPolicy"}}});Object(C.a)(D,"ContentSecurityPolicyPackage",null,[4,5]);var M=b(41);z.prototype.hNd=function(){return M.c(this)};Object(C.a)(z,"DiagnosticsRequest",
null,[]);var ba=b(4),V=b(525),aa=b(493),E=b(29);t.prototype.MWf=function(mb,Pa){try{this.r6g().send(this.yFh(mb,Pa))}catch(Da){B.ULS.sendTraceTag(6161306,201,10,"Could not send error report [{0}]",Da.toString())}};t.prototype.r6g=function(){var mb=new XMLHttpRequest;mb.open("POST",this.fFa,!0);mb.setRequestHeader("Content-Type","text/json; charset=utf-8");ba.AFrameworkApplication.userSessionId&&mb.setRequestHeader(aa.a.qCc,E.a.Xja(ba.AFrameworkApplication.userSessionId));this.EUa&&mb.setRequestHeader(aa.a.Z8a,
this.EUa);if(ba.AFrameworkApplication.Jd){var Pa=ba.AFrameworkApplication.Jd.QS;Pa&&mb.setRequestHeader(aa.a.QCc,Pa)}return mb};t.prototype.yFh=function(mb,Pa){if(!mb)return null;Pa=Pa?"<stack>"+Pa+"</stack>":"";var Da=new z;Da.Message=mb.message;Da.File=mb.source;Da.Line=mb.line;Da.Column=mb.column;Da.Stack=Pa;Da.ClientAppVersion=this.EUa;Da.AppType=this.r1;Da.AppMode=this.TEc;Da.DeobfuscateWithSourceMaps=this.oqg;ba.AFrameworkApplication.fa.ra("JavaScriptCrashJsonTagEnabled")&&(Da.SessionStartInfoJson=
ba.AFrameworkApplication.fa.appSettings.SessionStartInfoJson||"",ba.AFrameworkApplication.ag&&(Da.DataPlumber=M.c(ba.AFrameworkApplication.ag)),Da.IsShuttingDown=ba.AFrameworkApplication.Ng,Da.Flight=ba.AFrameworkApplication.QE,Da.ErrorName=V.a.uXe(mb));return Da.hNd()};Object(C.a)(t,"JavascriptErrorReporter",null,[905]);v.prototype.build=function(mb,Pa,Da,Ta,Sa){return new t(mb,Pa,Da,Ta,Sa)};Object(C.a)(v,"JavascriptErrorReporterFactory",null,[882]);w.prototype.fi=function(mb){mb.register(v,"Common.App.Diagnostics.JavascriptErrorReporterFactory").as("Common.IJavascriptErrorReporterFactory").Hc().Oc(function(){return new v})};
w.prototype.init=function(){};w.prototype.dispose=function(){};w.main=function(){Q.a.instance.gj(new w)};Ck.Object.defineProperties(w.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return"Common.App.Diagnostics"}}});Object(C.a)(w,"DiagnosticsPackage",null,[4,5]);var G=b(54),I=b(101),R=b(229),Y=b(37),U=b(162),ha=b(437),ta=b(38),xa=b(59),oa=b(40),qa=b(1312);Object(C.a)(u,"UlsUploadConfiguration",null,[]);var Ea=b(396);x.prototype.YRf=function(){this.Chb=[];this.XHc=!1};x.prototype.AV=
function(mb){1<this.Ceb?256>this.Chb.length?Array.add(this.Chb,mb):this.XHc=!0:(this.Fqa.YAg(mb),this.uti(mb)&&!this.BHe()?(this.BTe("LogIndicatesError in HandleTrace"),B.ULS.sendTraceTag(3731793,100,200,"Flushing error-level log (tag {0}) synchronously",Ea.a(mb.tag))):this.Fqa.kfi&&(this.Ttb(!1,!0),B.ULS.sendTraceTag(3731794,100,200,"Flushing asynchronously due to cache size")))};x.prototype.uti=function(mb){return!!mb&&(1===mb.Xtd||10===mb.level)};x.prototype.BHe=function(){return!1};x.prototype.dispose=
function(){this._disposing||(this._disposing=!0,this.uBh(),B.ULS.TOd(null),window.clearTimeout(this.HUa),window.clearTimeout(this.HRb),window.clearTimeout(this.KQb),this.KQb=this.HRb=this.HUa=0)};x.prototype.uBh=function(){this.mode=2;this.s4e();this.dvc=!1;this.LKe();this.BTe("FlushForAppClose")};x.prototype.nOb=function(mb,Pa){mb.bfb=this.iDb;return this.mdg(mb.serialize(),Pa)?(this.iDb++,!0):!1};x.prototype.mdg=function(mb,Pa){Pa=this.lkg||!Pa;this.Pg&&Pa||(this.Pg=new XMLHttpRequest);if(0===this.Pg.readyState||
4===this.Pg.readyState)return this.Pg.open("POST",this.f8,Pa),this.Pg.setRequestHeader("Content-Type","application/json"),this.Pg.setRequestHeader(x.tNd,this.zQc),Pa&&(this.Pg.timeout=this.zxg),this.Pg.send(mb),!0;mb={};B.ULS.sendTraceTag(3731796,100,50,"Could not initiate upload {0}",(mb.UploadId=this.iDb,mb.XhrReadyState=this.Pg.readyState,mb));return!1};x.prototype.iSi=function(){this.Pg&&this.Pg.abort()};x.prototype.rwc=function(mb,Pa,Da){try{return window.setTimeout(function(){B.ULS.sendTraceTag(3731797,
100,200,"Timeout ({0} ms) set by {1} is now firing.",Pa,Da);mb()},Pa)}catch(Ta){B.ULS.sendTraceTag(0,100,15,"SetTimeoutToLogOriginAndExecute: Calling Window.SetTimeout() failed with exception: {0}",Ta.toString());if(!this.QOd){this.QOd=!0;try{mb()}finally{this.QOd=!1}}return 0}};x.prototype.ZRf=function(){try{window.clearTimeout(this.HRb)}catch(mb){B.ULS.sendTraceTag(0,100,15,"ResetDelayedLoggingTimer: Calling Window.ClearTimeout() failed with exception: {0}",mb.toString())}this.HRb=this.rwc(Object(N.a)(this,
this.s4e,"handleDelayedLogs"),this.Hmg,"ResetDelayedLoggingTimer")};x.prototype.s4e=function(){var mb=this.Chb.length;if(mb){var Pa=this.Chb,Da=this.XHc;this.YRf();var Ta={};B.ULS.sendTraceTag(3731798,100,50,"HandleDelayedLogs {0}",(Ta.Count=mb,Ta.Limit=256,Ta.ExceededLimit=Da,Ta));this.$lb++;for(Da=0;Da<mb;Da++)this.AV(Pa[Da]);this.$lb--}this.ZRf()};x.prototype.kKd=function(){try{window.clearTimeout(this.KQb)}catch(mb){B.ULS.sendTraceTag(0,100,15,"ResetCadenceTimer: Calling Window.ClearTimeout() failed with exception: {0}",
mb.toString())}this.KQb=this.rwc(Object(N.a)(this,this.Ttb,"flushImpl"),this.yxg,"ResetCadenceTimer")};x.prototype.LKe=function(){this.mode=0;this.dvc&&(this.dvc=!1,this.Ttb())};x.prototype.nLb=function(mb){return 2===this.mode||1===this.mode&&!mb};x.prototype.BTe=function(mb){B.ULS.sendTraceTag(3731800,100,200,"Flushing Synchronous due to {0}",mb);this.Ttb(!0)};x.prototype.Rtb=function(){this.zTe(0)};x.prototype.zTe=function(mb){this.HUa||(this.HUa=this.rwc(Object(N.a)(this,this.Ttb,"flushImpl"),
mb,"FlushAsynchronous"))};x.prototype.Ttb=function(mb,Pa){this.$lb++;try{window.clearTimeout(this.HUa)}catch(Ta){B.ULS.sendTraceTag(0,100,15,"FlushImpl: Calling Window.ClearTimeout() failed with exception: {0}",Ta.toString())}this.HUa=0;if(this.Fqa.count)if(!Pa&&this.nLb(mb))B.ULS.sendTraceTag(3731801,100,200,"Not flushing ({0}) due to throttling",mb?"sync":"async"),this.dvc=!0;else{this.mode=mb?2:1;this.kKd();B.ULS.sendTraceTag(3731803,100,200,"Flushing ({0}) cached bULS logs ({1} logs)",mb?"sync":
"async",this.Fqa.count);try{var Da=this.nOb(this.Fqa,mb)}catch(Ta){this.iSi(),Da=!1}Da?(this.Fqa.reset(),this.kSb=0):(this.kSb++,this.kSb<x.Kof?this.zTe(x.ZKd):(this.Fqa.reset(),this.iDb++,this.kSb=0))}else this.kKd();this.$lb--};x.prototype.wwb=function(){};x.prototype.onb=function(){};Ck.Object.defineProperties(x.prototype,{Ceb:{configurable:!0,enumerable:!0,get:function(){return B.ULS.Ceb+this.$lb}},mode:{configurable:!0,enumerable:!0,get:function(){return this.WB},set:function(mb){var Pa=this.WB;
this.WB=mb;if(0===this.WB&&0!==Pa)try{var Da=this.XRc;this.XRc=0;window.clearTimeout(Da)}catch(Ta){B.ULS.sendTraceTag(0,100,15,"set_Mode: Calling Window.ClearTimeout() failed with exception: {0}",Ta.toString())}else 0!==this.WB&&0===Pa&&(this.XRc=this.rwc(Object(N.a)(this,this.LKe,"endThrottling"),this.Ywg,"ThrottlingMode Setter"))}}});x.Kof=3;x.ZKd=15E3;x.tNd="X-UserSessionId";Object(C.a)(x,"UploadingUlsHost",null,[30,3]);Object(C.a)(h,"UploadState",null,[]);var ka=b(84),za=b(593),La=Sys.EventArgs;
Wl(m,La);Object(C.a)(m,"UlsLoggingEventArgs",Sys.EventArgs,[]);var Ia=b(170);Wl(n,x);n.prototype.onb=function(mb){this.events.addHandler(n.W$f,mb)};n.prototype.kQi=function(mb,Pa){Pa.M6a(n.rUd)&&(this.Plb=this.n2e())};n.prototype.PIh=function(){return Error().stack};n.prototype.n2e=function(){var mb=null;if(this.oCa.ro(n.rUd)){mb=new Ia.a;for(var Pa=this.oCa.zw(n.rUd),Da=0;Da<Pa.length;Da++)mb.ia(Pa[Da],!0)}return mb};n.prototype.AV=function(mb){this.Plb||(this.Plb=this.n2e());if(this.Plb&&this.Plb.yb(mb.tag))try{!mb.H9c&&
this.zXc?mb.H9c=new za.a(Error()):mb.message+=". JsCallStack: "+this.PIh()}catch(Da){mb.message+=" [Failed to add callstack for this tag. BUlsExceptionLoggingIsEnabled="+this.zXc+" ("+Da.message+")]"}x.prototype.AV.call(this,mb);var Pa=this.events.getHandler(n.W$f);mb=new m(mb);Pa&&Pa(null,mb)};n.prototype.nOb=function(mb,Pa){if(this.dh){if(!this.Jwj)return!1;var Da=mb.serialize();if(0<ba.AFrameworkApplication.U0b&&Da.length>ba.AFrameworkApplication.U0b)return!1;mb.bfb=this.iDb++;if(this.Qvj())return this.jvc(this.f8,
Da),!0;this.Yle(this.f8,Da,Pa&&!this.tFb?0:3,1,Pa&&ba.AFrameworkApplication.Ng,mb.bfb,this.tFb,this.rEf);return!0}return x.prototype.nOb.call(this,mb,Pa)};n.prototype.nBd=function(mb){try{if(mb&&mb.data&&mb.data.responseHeaders&&n.rdc in mb.data.responseHeaders){var Pa=mb.data.responseHeaders[n.rdc];Pa!==this.Mlb&&(this.Mlb=Pa,n.EIf(mb.data.responseHeaders[n.M6e]))}}catch(Da){B.ULS.sendTraceTag(593847297,100,50,"Failed to process tag suppressions. [Message: {0}] [Stack: {1}]",Da.message,Da.stack)}};
n.prototype.Azd=function(mb){var Pa=this,Da=mb.data;if(!Da)B.ULS.sendTraceTag(5002497,100,15,"Request Item is null! RequestFailedEventArgs = {0}",mb);else if(13===Da.status)B.ULS.sendTraceTag(6399108,100,50,"Request timed out in the ClientRequestManager queue. Falling back to default XHR."),this.mdg(Da.request.get_body(),!1);else if(!Da.responseHeaders)B.ULS.sendTraceTag(5002498,100,15,"Item.ResponseHeader is null! RequestItem id = {0}, responseXml = {1}, data = {2}, HttpStatusCode = {3}",Da.id,Da.sQa,
Da.ke,Da.httpStatus);else if(!(n.Ybi in Da.responseHeaders||(mb=Da.httpStatus,400<=mb&&499>=mb))){var Ta=Da.state;Ta.ase>=x.Kof||window.setTimeout(function(){Pa.Yle(Da.request.get_url(),Da.request.get_body(),3,Ta.ase+1,!1,Ta.bfb,Ta.sessionId,Ta.version)},x.ZKd)}};n.prototype.Yle=function(mb,Pa,Da,Ta,Sa,Cb,cc,nc){this.dh.gm(mb,2,Pa,this.g6g(),!1,Da,Object(N.a)(this,this.nBd,"onSuccessfulUpload"),Object(N.a)(this,this.Azd,"onFailedUpload"),new h(Cb,Ta,cc,nc),null,Sa,this.oCa.Dd("BulsClientRequestManagerQueueTimeInMS",
3E4),void 0,"19",cc,void 0,nc,void 0,[n.rdc,n.M6e])};n.prototype.g6g=function(){var mb=null;this.Mlb&&(mb={},mb[n.rdc]=this.Mlb);if(this.zXc){var Pa=ba.AFrameworkApplication.sa,Da=null;Pa&&(Da=Pa.Qa);Da&&(mb||(mb={}),mb[n.t4h]=Da.oca,mb[n.u4h]=Da.Sj,mb[n.z4h]=ba.AFrameworkApplication.zei?"1":"0")}return mb};n.prototype.jvc=function(mb,Pa){this.dh.jvc(mb,Pa)};n.prototype.Qvj=function(){return ba.AFrameworkApplication.Ng||ba.AFrameworkApplication.hqd};n.gEh=function(mb,Pa,Da){mb=n.Ozg(mb,Pa);return mb=
n.SCg(mb,Da)};n.SCg=function(mb,Pa){if(!Pa)return mb;Pa=Pa.QS;return Pa?mb=P.a.El(mb,aa.a.RCc,Pa):mb};n.Ozg=function(mb,Pa){return Pa?P.a.El(mb,"build",ba.AFrameworkApplication.buildVersion):mb};n.EIf=function(mb){B.ULS.s2b();if(mb){mb=mb.split(",");mb=Gl(mb);for(var Pa=mb.next();!Pa.done;Pa=mb.next())Pa=parseInt(Pa.value),!isNaN(Pa)&&isFinite(Pa)&&B.ULS.UYb(Pa)}};Ck.Object.defineProperties(n.prototype,{events:{configurable:!0,enumerable:!0,get:function(){return this.sG||(this.sG=new Sys.EventHandlerList)}},
tFb:{configurable:!0,enumerable:!0,get:function(){return null}},rEf:{configurable:!0,enumerable:!0,get:function(){return null}},zXc:{configurable:!0,enumerable:!0,get:function(){return this.oCa.ra("BUlsExceptionLoggingIsEnabled")}},Xfj:{configurable:!0,enumerable:!0,get:function(){this.GPc||(this.GPc=this.oCa.Dd("bULSUploadRetryDelayWhenDisconnectedInMilliseconds",6E4));return this.GPc}},Jwj:{configurable:!0,enumerable:!0,get:function(){var mb=this.dh.q6a;return mb&&(new Date).getTime()-this.dh.$oi.getTime()>=
this.Xfj?!0:!mb}}});n.rdc="X-bULS-SuppressionETag";n.M6e="X-bULS-SuppressedTags";n.t4h="X-bULS-OfficeAppMode";n.u4h="X-bULS-OfficeAppType";n.z4h="X-bULS-UseSourceMaps";n.W$f="CommonUlsTraceEventKey";n.rUd="TagCallStackInclusionList";n.Ybi="X-InvalidUlsJson";Object(C.a)(n,"CommonUlsHost",x,[]);var Ya=b(97),tb=b(1);Wl(l,n);l.prototype.AV=function(mb){1===mb.Xtd&&tb.EwaSettings.isChangeGateEnabled("OfficeVSO:5335621_IdentifyClientAsserts")&&(mb.message="Assert: "+mb.message);n.prototype.AV.call(this,
mb)};l.prototype.BHe=function(){return!0};l.prototype.nOb=function(mb,Pa){if(ba.AFrameworkApplication.Ng&&ba.AFrameworkApplication.sbb)return!1;var Da=null;this.$&&(Da=this.$.Pb.Gc("UserAction","CommonUlsHostOverrides:UploadLogs"));Pa=!ba.AFrameworkApplication.sbb&&Pa;mb=n.prototype.nOb.call(this,mb,Pa);Da&&Da.stop();return mb};l.prototype.nBd=function(mb){n.prototype.nBd.call(this,mb);this.Pa.raiseEvent(this.tMj,mb)};l.prototype.Azd=function(mb){n.prototype.Azd.call(this,mb);this.Pa.raiseEvent(this.qMj,
mb)};Ck.Object.defineProperties(l.prototype,{$:{configurable:!0,enumerable:!0,get:function(){this.xb||(this.xb=0<xa.a.getRegisteredEwaInstances().length?xa.a.Yr(document.body):null);return this.xb}}});Object(C.a)(l,"CommonUlsHostOverrides",n,[479,30,3]);f.prototype.D4g=function(mb){return new l(mb)};Object(C.a)(f,"CommonHostFactory",null,[519]);var Tb=b(53),va=ta.a;Wl(e,va);e.prototype.onb=function(mb){this.$2b.onb(mb)};e.prototype.AV=function(mb){this.$2b.AV(mb)};e.prototype.wwb=function(mb){this.$2b.wwb(mb)};
e.prototype.Rtb=function(){this.$2b.Rtb()};e.ka=function(mb,Pa){Pa=void 0===Pa?null:Pa;var Da=new U.a;Object(ha.a)(e,ba.AFrameworkApplication.OSa)||(Pa=Pa||new f,oa.a.X9h(function(){if(ba.AFrameworkApplication.browserUlsIsEnabled){var Ta=mb+"/RemoteUls.ashx";e.$&&(Ta=e.bCg(Ta));Ta=Pa.D4g(Ta);ba.AFrameworkApplication.OSa=Ta;B.ULS.wRa(50);B.ULS.TOd(Ta);Da.setResult(new e(Ta))}else B.ULS.disable()},!ba.AFrameworkApplication.Muj()));return Da.task};e.bCg=function(mb){var Pa=e.$&&Tb.d(e.$)?e.$.workbookContext.BuildVersion:
e.$.ya.BuildVersion;return P.a.El(mb,"officeserverversion",Pa)};Ck.Object.defineProperties(e,{$:{configurable:!0,enumerable:!0,get:function(){e.xb||(e.xb=0<xa.a.getRegisteredEwaInstances().length?xa.a.Yr(document.body):null);return e.xb}}});e.xb=null;Object(C.a)(e,"EwaUlsHost",ta.a,[479,30,3]);var la=R.a;Wl(c,la);c.prototype.create=function(){var mb=this;Y.TaskExtensions.Ba(e.ka(this.Jda),function(Pa){Pa=Pa.result;I.a.vl.Ga(135,Pa);mb.Eb(Pa)},this.la)};Object(C.a)(c,"EwaUlsHostFactory",R.a,[]);var $a=
b(160),Ra=b(35);a.prototype.I_i=function(mb,Pa,Da){!mb&&Pa.source&&(mb=Ra.a.mq(this.vxd,Pa.source)+1,this.vxd[Pa.source]=mb,mb-1&mb||B.ULS.sendTraceTag(537155536,0,15,"{0} errors seen for location={1}",mb,Pa.source));Pa.source&&1!==Ra.a.mq(this.vxd,Pa.source,1)||(B.ULS.sendTraceTag(537155535,0,50,"JavaSctipCrashProcessor.ProcessJavascriptError: Sending request to log JavaScript crash in the server"),this.Ini.MWf(Pa,Da))};Ck.Object.defineProperties(a.prototype,{vxd:{configurable:!0,enumerable:!0,get:function(){return this.rbe||
(this.rbe={})}}});Object(C.a)(a,"JavaScriptCrashProcessor",null,[466]);var eb=b(62);Type.registerNamespace("_Ewa");Object(y.a)();Type.registerNamespace("Common.App.ContentSecurityPolicy");D.main();Type.registerNamespace("Common.App.Diagnostics");w.main();Type.registerNamespace("DiagUse");I.a.vl.Ga(43,new c(G.a.current.UN.ServerUriBase));(function(){try{$a.a.v3e().CWCT(function(mb){try{if(I.a.vl.za(42))B.ULS.sendTraceTag(537155532,0,50,"JavaScriptCrashProcessorBootstrapper: already initialized");else{var Pa=
mb.result,Da=ka.a.instance.resolve("Common.IJavascriptErrorReporterFactory").build(G.a.current.UN.ServerUriBase+Pa.LayoutsRelativeUri+"/diagnostics.ashx",Pa.BuildVersion,1,0,!0);I.a.vl.Ga(42,new a(Da));B.ULS.sendTraceTag(537155533,0,50,"JavaScriptCrashProcessorBootstrapper: initialized and ready to be used")}}catch(Ta){B.ULS.sendTraceTag(537155531,0,15,"JavaScriptCrashProcessorBootstrapper: An exception occured while initializing JavascriptErrorProcessor, Message: {0}, Callstack: {1}",Ta.message,
Ta.stack)}},null,3,eb.a.current)}catch(mb){B.ULS.sendTraceTag(537155530,0,15,"JavaScriptCrashProcessorBootstrapper: an exception occured, Message: {0}, Callstack: {1}",mb.message,mb.stack)}})()}}]);

//# sourceMappingURL=https://artifacts.dev.azure.com/office/_apis/symbol/symsrv/EwaDS.tmcore.js.map/5e2d58b83ff8eacc7c51c77a778b0fb5/EwaDS.tmcore.js.map